//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor_Prototype.DocumentEditorWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentPattern", Namespace="http://documentservice.agh.org/")]
    [System.SerializableAttribute()]
    public partial class DocumentPattern : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double PageWidthField;
        
        private double PageHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Editor_Prototype.DocumentEditorWebService.ContentPattern[] ContentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double PageWidth {
            get {
                return this.PageWidthField;
            }
            set {
                if ((this.PageWidthField.Equals(value) != true)) {
                    this.PageWidthField = value;
                    this.RaisePropertyChanged("PageWidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double PageHeight {
            get {
                return this.PageHeightField;
            }
            set {
                if ((this.PageHeightField.Equals(value) != true)) {
                    this.PageHeightField = value;
                    this.RaisePropertyChanged("PageHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Editor_Prototype.DocumentEditorWebService.ContentPattern[] Contents {
            get {
                return this.ContentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentsField, value) != true)) {
                    this.ContentsField = value;
                    this.RaisePropertyChanged("Contents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentPattern", Namespace="http://documentservice.agh.org/")]
    [System.SerializableAttribute()]
    public partial class ContentPattern : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double XField;
        
        private double YField;
        
        private double WidthField;
        
        private double HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://documentservice.agh.org/")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentPatternIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Editor_Prototype.DocumentEditorWebService.DocumentData[] DocumentDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentPatternId {
            get {
                return this.DocumentPatternIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentPatternIdField, value) != true)) {
                    this.DocumentPatternIdField = value;
                    this.RaisePropertyChanged("DocumentPatternId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Editor_Prototype.DocumentEditorWebService.DocumentData[] DocumentData {
            get {
                return this.DocumentDataField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentDataField, value) != true)) {
                    this.DocumentDataField = value;
                    this.RaisePropertyChanged("DocumentData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentData", Namespace="http://documentservice.agh.org/")]
    [System.SerializableAttribute()]
    public partial class DocumentData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ContentId {
            get {
                return this.ContentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentIdField, value) != true)) {
                    this.ContentIdField = value;
                    this.RaisePropertyChanged("ContentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://documentservice.agh.org/", ConfigurationName="DocumentEditorWebService.DocumentEditorServiceSoap")]
    public interface DocumentEditorServiceSoap {
        
        // CODEGEN: Generating message contract since element name CreateDocumentPatternResult from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/CreateDocumentPattern", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternResponse CreateDocumentPattern(Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/ClearAllDocumentPatterns", ReplyAction="*")]
        void ClearAllDocumentPatterns();
        
        // CODEGEN: Generating message contract since element name documentPatternId from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/GetDocumentPattern", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.GetDocumentPatternResponse GetDocumentPattern(Editor_Prototype.DocumentEditorWebService.GetDocumentPatternRequest request);
        
        // CODEGEN: Generating message contract since element name documentPattern from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/SaveDocumentPattern", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternResponse SaveDocumentPattern(Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllDocumentPatternsResult from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/GetAllDocumentPatterns", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsResponse GetAllDocumentPatterns(Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsRequest request);
        
        // CODEGEN: Generating message contract since element name docPattern from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/AddContentToDocumentPattern", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternResponse AddContentToDocumentPattern(Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternRequest request);
        
        // CODEGEN: Generating message contract since element name CreateContentPatternResult from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/CreateContentPattern", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.CreateContentPatternResponse CreateContentPattern(Editor_Prototype.DocumentEditorWebService.CreateContentPatternRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/ClearAllContentPattenrs", ReplyAction="*")]
        void ClearAllContentPattenrs();
        
        // CODEGEN: Generating message contract since element name contentId from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/GetContentPattern", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.GetContentPatternResponse GetContentPattern(Editor_Prototype.DocumentEditorWebService.GetContentPatternRequest request);
        
        // CODEGEN: Generating message contract since element name contentPattern from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/SaveContentPattern", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.SaveContentPatternResponse SaveContentPattern(Editor_Prototype.DocumentEditorWebService.SaveContentPatternRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllContentPatternsResult from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/GetAllContentPatterns", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsResponse GetAllContentPatterns(Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsRequest request);
        
        // CODEGEN: Generating message contract since element name CreateDocumentResult from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/CreateDocument", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.CreateDocumentResponse CreateDocument(Editor_Prototype.DocumentEditorWebService.CreateDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/ClearAllDocuments", ReplyAction="*")]
        void ClearAllDocuments();
        
        // CODEGEN: Generating message contract since element name documentId from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/GetDocument", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.GetDocumentResponse GetDocument(Editor_Prototype.DocumentEditorWebService.GetDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name document from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/SaveDocument", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.SaveDocumentResponse SaveDocument(Editor_Prototype.DocumentEditorWebService.SaveDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllDocumentsResult from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/GetAllDocuments", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.GetAllDocumentsResponse GetAllDocuments(Editor_Prototype.DocumentEditorWebService.GetAllDocumentsRequest request);
        
        // CODEGEN: Generating message contract since element name document from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/AddDocumentData", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.AddDocumentDataResponse AddDocumentData(Editor_Prototype.DocumentEditorWebService.AddDocumentDataRequest request);
        
        // CODEGEN: Generating message contract since element name document from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/GetDocumentData", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.GetDocumentDataResponse GetDocumentData(Editor_Prototype.DocumentEditorWebService.GetDocumentDataRequest request);
        
        // CODEGEN: Generating message contract since element name document from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/ClearDocumentData", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.ClearDocumentDataResponse ClearDocumentData(Editor_Prototype.DocumentEditorWebService.ClearDocumentDataRequest request);
        
        // CODEGEN: Generating message contract since element name document from namespace http://documentservice.agh.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://documentservice.agh.org/InitDocumentContentsData", ReplyAction="*")]
        Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataResponse InitDocumentContentsData(Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDocumentPatternRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDocumentPattern", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternRequestBody Body;
        
        public CreateDocumentPatternRequest() {
        }
        
        public CreateDocumentPatternRequest(Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateDocumentPatternRequestBody {
        
        public CreateDocumentPatternRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDocumentPatternResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDocumentPatternResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternResponseBody Body;
        
        public CreateDocumentPatternResponse() {
        }
        
        public CreateDocumentPatternResponse(Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class CreateDocumentPatternResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.DocumentPattern CreateDocumentPatternResult;
        
        public CreateDocumentPatternResponseBody() {
        }
        
        public CreateDocumentPatternResponseBody(Editor_Prototype.DocumentEditorWebService.DocumentPattern CreateDocumentPatternResult) {
            this.CreateDocumentPatternResult = CreateDocumentPatternResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentPatternRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentPattern", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetDocumentPatternRequestBody Body;
        
        public GetDocumentPatternRequest() {
        }
        
        public GetDocumentPatternRequest(Editor_Prototype.DocumentEditorWebService.GetDocumentPatternRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class GetDocumentPatternRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documentPatternId;
        
        public GetDocumentPatternRequestBody() {
        }
        
        public GetDocumentPatternRequestBody(string documentPatternId) {
            this.documentPatternId = documentPatternId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentPatternResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentPatternResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetDocumentPatternResponseBody Body;
        
        public GetDocumentPatternResponse() {
        }
        
        public GetDocumentPatternResponse(Editor_Prototype.DocumentEditorWebService.GetDocumentPatternResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class GetDocumentPatternResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.DocumentPattern GetDocumentPatternResult;
        
        public GetDocumentPatternResponseBody() {
        }
        
        public GetDocumentPatternResponseBody(Editor_Prototype.DocumentEditorWebService.DocumentPattern GetDocumentPatternResult) {
            this.GetDocumentPatternResult = GetDocumentPatternResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDocumentPatternRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDocumentPattern", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternRequestBody Body;
        
        public SaveDocumentPatternRequest() {
        }
        
        public SaveDocumentPatternRequest(Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class SaveDocumentPatternRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.DocumentPattern documentPattern;
        
        public SaveDocumentPatternRequestBody() {
        }
        
        public SaveDocumentPatternRequestBody(Editor_Prototype.DocumentEditorWebService.DocumentPattern documentPattern) {
            this.documentPattern = documentPattern;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDocumentPatternResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDocumentPatternResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternResponseBody Body;
        
        public SaveDocumentPatternResponse() {
        }
        
        public SaveDocumentPatternResponse(Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveDocumentPatternResponseBody {
        
        public SaveDocumentPatternResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDocumentPatternsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDocumentPatterns", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsRequestBody Body;
        
        public GetAllDocumentPatternsRequest() {
        }
        
        public GetAllDocumentPatternsRequest(Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDocumentPatternsRequestBody {
        
        public GetAllDocumentPatternsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDocumentPatternsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDocumentPatternsResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsResponseBody Body;
        
        public GetAllDocumentPatternsResponse() {
        }
        
        public GetAllDocumentPatternsResponse(Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class GetAllDocumentPatternsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.DocumentPattern[] GetAllDocumentPatternsResult;
        
        public GetAllDocumentPatternsResponseBody() {
        }
        
        public GetAllDocumentPatternsResponseBody(Editor_Prototype.DocumentEditorWebService.DocumentPattern[] GetAllDocumentPatternsResult) {
            this.GetAllDocumentPatternsResult = GetAllDocumentPatternsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContentToDocumentPatternRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContentToDocumentPattern", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternRequestBody Body;
        
        public AddContentToDocumentPatternRequest() {
        }
        
        public AddContentToDocumentPatternRequest(Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class AddContentToDocumentPatternRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.DocumentPattern docPattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Editor_Prototype.DocumentEditorWebService.ContentPattern contentPattern;
        
        public AddContentToDocumentPatternRequestBody() {
        }
        
        public AddContentToDocumentPatternRequestBody(Editor_Prototype.DocumentEditorWebService.DocumentPattern docPattern, Editor_Prototype.DocumentEditorWebService.ContentPattern contentPattern) {
            this.docPattern = docPattern;
            this.contentPattern = contentPattern;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContentToDocumentPatternResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContentToDocumentPatternResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternResponseBody Body;
        
        public AddContentToDocumentPatternResponse() {
        }
        
        public AddContentToDocumentPatternResponse(Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class AddContentToDocumentPatternResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.DocumentPattern AddContentToDocumentPatternResult;
        
        public AddContentToDocumentPatternResponseBody() {
        }
        
        public AddContentToDocumentPatternResponseBody(Editor_Prototype.DocumentEditorWebService.DocumentPattern AddContentToDocumentPatternResult) {
            this.AddContentToDocumentPatternResult = AddContentToDocumentPatternResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateContentPatternRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateContentPattern", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.CreateContentPatternRequestBody Body;
        
        public CreateContentPatternRequest() {
        }
        
        public CreateContentPatternRequest(Editor_Prototype.DocumentEditorWebService.CreateContentPatternRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateContentPatternRequestBody {
        
        public CreateContentPatternRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateContentPatternResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateContentPatternResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.CreateContentPatternResponseBody Body;
        
        public CreateContentPatternResponse() {
        }
        
        public CreateContentPatternResponse(Editor_Prototype.DocumentEditorWebService.CreateContentPatternResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class CreateContentPatternResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.ContentPattern CreateContentPatternResult;
        
        public CreateContentPatternResponseBody() {
        }
        
        public CreateContentPatternResponseBody(Editor_Prototype.DocumentEditorWebService.ContentPattern CreateContentPatternResult) {
            this.CreateContentPatternResult = CreateContentPatternResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentPatternRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentPattern", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetContentPatternRequestBody Body;
        
        public GetContentPatternRequest() {
        }
        
        public GetContentPatternRequest(Editor_Prototype.DocumentEditorWebService.GetContentPatternRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class GetContentPatternRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contentId;
        
        public GetContentPatternRequestBody() {
        }
        
        public GetContentPatternRequestBody(string contentId) {
            this.contentId = contentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContentPatternResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContentPatternResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetContentPatternResponseBody Body;
        
        public GetContentPatternResponse() {
        }
        
        public GetContentPatternResponse(Editor_Prototype.DocumentEditorWebService.GetContentPatternResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class GetContentPatternResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.ContentPattern GetContentPatternResult;
        
        public GetContentPatternResponseBody() {
        }
        
        public GetContentPatternResponseBody(Editor_Prototype.DocumentEditorWebService.ContentPattern GetContentPatternResult) {
            this.GetContentPatternResult = GetContentPatternResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveContentPatternRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveContentPattern", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.SaveContentPatternRequestBody Body;
        
        public SaveContentPatternRequest() {
        }
        
        public SaveContentPatternRequest(Editor_Prototype.DocumentEditorWebService.SaveContentPatternRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class SaveContentPatternRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.ContentPattern contentPattern;
        
        public SaveContentPatternRequestBody() {
        }
        
        public SaveContentPatternRequestBody(Editor_Prototype.DocumentEditorWebService.ContentPattern contentPattern) {
            this.contentPattern = contentPattern;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveContentPatternResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveContentPatternResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.SaveContentPatternResponseBody Body;
        
        public SaveContentPatternResponse() {
        }
        
        public SaveContentPatternResponse(Editor_Prototype.DocumentEditorWebService.SaveContentPatternResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveContentPatternResponseBody {
        
        public SaveContentPatternResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllContentPatternsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllContentPatterns", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsRequestBody Body;
        
        public GetAllContentPatternsRequest() {
        }
        
        public GetAllContentPatternsRequest(Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllContentPatternsRequestBody {
        
        public GetAllContentPatternsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllContentPatternsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllContentPatternsResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsResponseBody Body;
        
        public GetAllContentPatternsResponse() {
        }
        
        public GetAllContentPatternsResponse(Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class GetAllContentPatternsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.ContentPattern[] GetAllContentPatternsResult;
        
        public GetAllContentPatternsResponseBody() {
        }
        
        public GetAllContentPatternsResponseBody(Editor_Prototype.DocumentEditorWebService.ContentPattern[] GetAllContentPatternsResult) {
            this.GetAllContentPatternsResult = GetAllContentPatternsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDocument", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.CreateDocumentRequestBody Body;
        
        public CreateDocumentRequest() {
        }
        
        public CreateDocumentRequest(Editor_Prototype.DocumentEditorWebService.CreateDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateDocumentRequestBody {
        
        public CreateDocumentRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDocumentResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.CreateDocumentResponseBody Body;
        
        public CreateDocumentResponse() {
        }
        
        public CreateDocumentResponse(Editor_Prototype.DocumentEditorWebService.CreateDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class CreateDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.Document CreateDocumentResult;
        
        public CreateDocumentResponseBody() {
        }
        
        public CreateDocumentResponseBody(Editor_Prototype.DocumentEditorWebService.Document CreateDocumentResult) {
            this.CreateDocumentResult = CreateDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocument", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetDocumentRequestBody Body;
        
        public GetDocumentRequest() {
        }
        
        public GetDocumentRequest(Editor_Prototype.DocumentEditorWebService.GetDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class GetDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string documentId;
        
        public GetDocumentRequestBody() {
        }
        
        public GetDocumentRequestBody(string documentId) {
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetDocumentResponseBody Body;
        
        public GetDocumentResponse() {
        }
        
        public GetDocumentResponse(Editor_Prototype.DocumentEditorWebService.GetDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDocumentResponseBody {
        
        public GetDocumentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDocument", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.SaveDocumentRequestBody Body;
        
        public SaveDocumentRequest() {
        }
        
        public SaveDocumentRequest(Editor_Prototype.DocumentEditorWebService.SaveDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class SaveDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.Document document;
        
        public SaveDocumentRequestBody() {
        }
        
        public SaveDocumentRequestBody(Editor_Prototype.DocumentEditorWebService.Document document) {
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDocumentResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.SaveDocumentResponseBody Body;
        
        public SaveDocumentResponse() {
        }
        
        public SaveDocumentResponse(Editor_Prototype.DocumentEditorWebService.SaveDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveDocumentResponseBody {
        
        public SaveDocumentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDocumentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDocuments", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetAllDocumentsRequestBody Body;
        
        public GetAllDocumentsRequest() {
        }
        
        public GetAllDocumentsRequest(Editor_Prototype.DocumentEditorWebService.GetAllDocumentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDocumentsRequestBody {
        
        public GetAllDocumentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDocumentsResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetAllDocumentsResponseBody Body;
        
        public GetAllDocumentsResponse() {
        }
        
        public GetAllDocumentsResponse(Editor_Prototype.DocumentEditorWebService.GetAllDocumentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class GetAllDocumentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.Document[] GetAllDocumentsResult;
        
        public GetAllDocumentsResponseBody() {
        }
        
        public GetAllDocumentsResponseBody(Editor_Prototype.DocumentEditorWebService.Document[] GetAllDocumentsResult) {
            this.GetAllDocumentsResult = GetAllDocumentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDocumentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDocumentData", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.AddDocumentDataRequestBody Body;
        
        public AddDocumentDataRequest() {
        }
        
        public AddDocumentDataRequest(Editor_Prototype.DocumentEditorWebService.AddDocumentDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class AddDocumentDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.Document document;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string data;
        
        public AddDocumentDataRequestBody() {
        }
        
        public AddDocumentDataRequestBody(Editor_Prototype.DocumentEditorWebService.Document document, string contentId, string data) {
            this.document = document;
            this.contentId = contentId;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDocumentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDocumentDataResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.AddDocumentDataResponseBody Body;
        
        public AddDocumentDataResponse() {
        }
        
        public AddDocumentDataResponse(Editor_Prototype.DocumentEditorWebService.AddDocumentDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class AddDocumentDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.Document AddDocumentDataResult;
        
        public AddDocumentDataResponseBody() {
        }
        
        public AddDocumentDataResponseBody(Editor_Prototype.DocumentEditorWebService.Document AddDocumentDataResult) {
            this.AddDocumentDataResult = AddDocumentDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentData", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetDocumentDataRequestBody Body;
        
        public GetDocumentDataRequest() {
        }
        
        public GetDocumentDataRequest(Editor_Prototype.DocumentEditorWebService.GetDocumentDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class GetDocumentDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.Document document;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contentId;
        
        public GetDocumentDataRequestBody() {
        }
        
        public GetDocumentDataRequestBody(Editor_Prototype.DocumentEditorWebService.Document document, string contentId) {
            this.document = document;
            this.contentId = contentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentDataResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.GetDocumentDataResponseBody Body;
        
        public GetDocumentDataResponse() {
        }
        
        public GetDocumentDataResponse(Editor_Prototype.DocumentEditorWebService.GetDocumentDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class GetDocumentDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDocumentDataResult;
        
        public GetDocumentDataResponseBody() {
        }
        
        public GetDocumentDataResponseBody(string GetDocumentDataResult) {
            this.GetDocumentDataResult = GetDocumentDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClearDocumentDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClearDocumentData", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.ClearDocumentDataRequestBody Body;
        
        public ClearDocumentDataRequest() {
        }
        
        public ClearDocumentDataRequest(Editor_Prototype.DocumentEditorWebService.ClearDocumentDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class ClearDocumentDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.Document document;
        
        public ClearDocumentDataRequestBody() {
        }
        
        public ClearDocumentDataRequestBody(Editor_Prototype.DocumentEditorWebService.Document document) {
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClearDocumentDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClearDocumentDataResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.ClearDocumentDataResponseBody Body;
        
        public ClearDocumentDataResponse() {
        }
        
        public ClearDocumentDataResponse(Editor_Prototype.DocumentEditorWebService.ClearDocumentDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ClearDocumentDataResponseBody {
        
        public ClearDocumentDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitDocumentContentsDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitDocumentContentsData", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataRequestBody Body;
        
        public InitDocumentContentsDataRequest() {
        }
        
        public InitDocumentContentsDataRequest(Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class InitDocumentContentsDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.Document document;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Editor_Prototype.DocumentEditorWebService.DocumentPattern documentPattern;
        
        public InitDocumentContentsDataRequestBody() {
        }
        
        public InitDocumentContentsDataRequestBody(Editor_Prototype.DocumentEditorWebService.Document document, Editor_Prototype.DocumentEditorWebService.DocumentPattern documentPattern) {
            this.document = document;
            this.documentPattern = documentPattern;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InitDocumentContentsDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InitDocumentContentsDataResponse", Namespace="http://documentservice.agh.org/", Order=0)]
        public Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataResponseBody Body;
        
        public InitDocumentContentsDataResponse() {
        }
        
        public InitDocumentContentsDataResponse(Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://documentservice.agh.org/")]
    public partial class InitDocumentContentsDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Editor_Prototype.DocumentEditorWebService.Document InitDocumentContentsDataResult;
        
        public InitDocumentContentsDataResponseBody() {
        }
        
        public InitDocumentContentsDataResponseBody(Editor_Prototype.DocumentEditorWebService.Document InitDocumentContentsDataResult) {
            this.InitDocumentContentsDataResult = InitDocumentContentsDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentEditorServiceSoapChannel : Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentEditorServiceSoapClient : System.ServiceModel.ClientBase<Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap>, Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap {
        
        public DocumentEditorServiceSoapClient() {
        }
        
        public DocumentEditorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentEditorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentEditorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentEditorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.CreateDocumentPattern(Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternRequest request) {
            return base.Channel.CreateDocumentPattern(request);
        }
        
        public Editor_Prototype.DocumentEditorWebService.DocumentPattern CreateDocumentPattern() {
            Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternRequest inValue = new Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternRequestBody();
            Editor_Prototype.DocumentEditorWebService.CreateDocumentPatternResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).CreateDocumentPattern(inValue);
            return retVal.Body.CreateDocumentPatternResult;
        }
        
        public void ClearAllDocumentPatterns() {
            base.Channel.ClearAllDocumentPatterns();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.GetDocumentPatternResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.GetDocumentPattern(Editor_Prototype.DocumentEditorWebService.GetDocumentPatternRequest request) {
            return base.Channel.GetDocumentPattern(request);
        }
        
        public Editor_Prototype.DocumentEditorWebService.DocumentPattern GetDocumentPattern(string documentPatternId) {
            Editor_Prototype.DocumentEditorWebService.GetDocumentPatternRequest inValue = new Editor_Prototype.DocumentEditorWebService.GetDocumentPatternRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.GetDocumentPatternRequestBody();
            inValue.Body.documentPatternId = documentPatternId;
            Editor_Prototype.DocumentEditorWebService.GetDocumentPatternResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).GetDocumentPattern(inValue);
            return retVal.Body.GetDocumentPatternResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.SaveDocumentPattern(Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternRequest request) {
            return base.Channel.SaveDocumentPattern(request);
        }
        
        public void SaveDocumentPattern(Editor_Prototype.DocumentEditorWebService.DocumentPattern documentPattern) {
            Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternRequest inValue = new Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternRequestBody();
            inValue.Body.documentPattern = documentPattern;
            Editor_Prototype.DocumentEditorWebService.SaveDocumentPatternResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).SaveDocumentPattern(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.GetAllDocumentPatterns(Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsRequest request) {
            return base.Channel.GetAllDocumentPatterns(request);
        }
        
        public Editor_Prototype.DocumentEditorWebService.DocumentPattern[] GetAllDocumentPatterns() {
            Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsRequest inValue = new Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsRequestBody();
            Editor_Prototype.DocumentEditorWebService.GetAllDocumentPatternsResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).GetAllDocumentPatterns(inValue);
            return retVal.Body.GetAllDocumentPatternsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.AddContentToDocumentPattern(Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternRequest request) {
            return base.Channel.AddContentToDocumentPattern(request);
        }
        
        public Editor_Prototype.DocumentEditorWebService.DocumentPattern AddContentToDocumentPattern(Editor_Prototype.DocumentEditorWebService.DocumentPattern docPattern, Editor_Prototype.DocumentEditorWebService.ContentPattern contentPattern) {
            Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternRequest inValue = new Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternRequestBody();
            inValue.Body.docPattern = docPattern;
            inValue.Body.contentPattern = contentPattern;
            Editor_Prototype.DocumentEditorWebService.AddContentToDocumentPatternResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).AddContentToDocumentPattern(inValue);
            return retVal.Body.AddContentToDocumentPatternResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.CreateContentPatternResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.CreateContentPattern(Editor_Prototype.DocumentEditorWebService.CreateContentPatternRequest request) {
            return base.Channel.CreateContentPattern(request);
        }
        
        public Editor_Prototype.DocumentEditorWebService.ContentPattern CreateContentPattern() {
            Editor_Prototype.DocumentEditorWebService.CreateContentPatternRequest inValue = new Editor_Prototype.DocumentEditorWebService.CreateContentPatternRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.CreateContentPatternRequestBody();
            Editor_Prototype.DocumentEditorWebService.CreateContentPatternResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).CreateContentPattern(inValue);
            return retVal.Body.CreateContentPatternResult;
        }
        
        public void ClearAllContentPattenrs() {
            base.Channel.ClearAllContentPattenrs();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.GetContentPatternResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.GetContentPattern(Editor_Prototype.DocumentEditorWebService.GetContentPatternRequest request) {
            return base.Channel.GetContentPattern(request);
        }
        
        public Editor_Prototype.DocumentEditorWebService.ContentPattern GetContentPattern(string contentId) {
            Editor_Prototype.DocumentEditorWebService.GetContentPatternRequest inValue = new Editor_Prototype.DocumentEditorWebService.GetContentPatternRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.GetContentPatternRequestBody();
            inValue.Body.contentId = contentId;
            Editor_Prototype.DocumentEditorWebService.GetContentPatternResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).GetContentPattern(inValue);
            return retVal.Body.GetContentPatternResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.SaveContentPatternResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.SaveContentPattern(Editor_Prototype.DocumentEditorWebService.SaveContentPatternRequest request) {
            return base.Channel.SaveContentPattern(request);
        }
        
        public void SaveContentPattern(Editor_Prototype.DocumentEditorWebService.ContentPattern contentPattern) {
            Editor_Prototype.DocumentEditorWebService.SaveContentPatternRequest inValue = new Editor_Prototype.DocumentEditorWebService.SaveContentPatternRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.SaveContentPatternRequestBody();
            inValue.Body.contentPattern = contentPattern;
            Editor_Prototype.DocumentEditorWebService.SaveContentPatternResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).SaveContentPattern(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.GetAllContentPatterns(Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsRequest request) {
            return base.Channel.GetAllContentPatterns(request);
        }
        
        public Editor_Prototype.DocumentEditorWebService.ContentPattern[] GetAllContentPatterns() {
            Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsRequest inValue = new Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsRequestBody();
            Editor_Prototype.DocumentEditorWebService.GetAllContentPatternsResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).GetAllContentPatterns(inValue);
            return retVal.Body.GetAllContentPatternsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.CreateDocumentResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.CreateDocument(Editor_Prototype.DocumentEditorWebService.CreateDocumentRequest request) {
            return base.Channel.CreateDocument(request);
        }
        
        public Editor_Prototype.DocumentEditorWebService.Document CreateDocument() {
            Editor_Prototype.DocumentEditorWebService.CreateDocumentRequest inValue = new Editor_Prototype.DocumentEditorWebService.CreateDocumentRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.CreateDocumentRequestBody();
            Editor_Prototype.DocumentEditorWebService.CreateDocumentResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).CreateDocument(inValue);
            return retVal.Body.CreateDocumentResult;
        }
        
        public void ClearAllDocuments() {
            base.Channel.ClearAllDocuments();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.GetDocumentResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.GetDocument(Editor_Prototype.DocumentEditorWebService.GetDocumentRequest request) {
            return base.Channel.GetDocument(request);
        }
        
        public void GetDocument(string documentId) {
            Editor_Prototype.DocumentEditorWebService.GetDocumentRequest inValue = new Editor_Prototype.DocumentEditorWebService.GetDocumentRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.GetDocumentRequestBody();
            inValue.Body.documentId = documentId;
            Editor_Prototype.DocumentEditorWebService.GetDocumentResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).GetDocument(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.SaveDocumentResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.SaveDocument(Editor_Prototype.DocumentEditorWebService.SaveDocumentRequest request) {
            return base.Channel.SaveDocument(request);
        }
        
        public void SaveDocument(Editor_Prototype.DocumentEditorWebService.Document document) {
            Editor_Prototype.DocumentEditorWebService.SaveDocumentRequest inValue = new Editor_Prototype.DocumentEditorWebService.SaveDocumentRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.SaveDocumentRequestBody();
            inValue.Body.document = document;
            Editor_Prototype.DocumentEditorWebService.SaveDocumentResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).SaveDocument(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.GetAllDocumentsResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.GetAllDocuments(Editor_Prototype.DocumentEditorWebService.GetAllDocumentsRequest request) {
            return base.Channel.GetAllDocuments(request);
        }
        
        public Editor_Prototype.DocumentEditorWebService.Document[] GetAllDocuments() {
            Editor_Prototype.DocumentEditorWebService.GetAllDocumentsRequest inValue = new Editor_Prototype.DocumentEditorWebService.GetAllDocumentsRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.GetAllDocumentsRequestBody();
            Editor_Prototype.DocumentEditorWebService.GetAllDocumentsResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).GetAllDocuments(inValue);
            return retVal.Body.GetAllDocumentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.AddDocumentDataResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.AddDocumentData(Editor_Prototype.DocumentEditorWebService.AddDocumentDataRequest request) {
            return base.Channel.AddDocumentData(request);
        }
        
        public Editor_Prototype.DocumentEditorWebService.Document AddDocumentData(Editor_Prototype.DocumentEditorWebService.Document document, string contentId, string data) {
            Editor_Prototype.DocumentEditorWebService.AddDocumentDataRequest inValue = new Editor_Prototype.DocumentEditorWebService.AddDocumentDataRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.AddDocumentDataRequestBody();
            inValue.Body.document = document;
            inValue.Body.contentId = contentId;
            inValue.Body.data = data;
            Editor_Prototype.DocumentEditorWebService.AddDocumentDataResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).AddDocumentData(inValue);
            return retVal.Body.AddDocumentDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.GetDocumentDataResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.GetDocumentData(Editor_Prototype.DocumentEditorWebService.GetDocumentDataRequest request) {
            return base.Channel.GetDocumentData(request);
        }
        
        public string GetDocumentData(Editor_Prototype.DocumentEditorWebService.Document document, string contentId) {
            Editor_Prototype.DocumentEditorWebService.GetDocumentDataRequest inValue = new Editor_Prototype.DocumentEditorWebService.GetDocumentDataRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.GetDocumentDataRequestBody();
            inValue.Body.document = document;
            inValue.Body.contentId = contentId;
            Editor_Prototype.DocumentEditorWebService.GetDocumentDataResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).GetDocumentData(inValue);
            return retVal.Body.GetDocumentDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.ClearDocumentDataResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.ClearDocumentData(Editor_Prototype.DocumentEditorWebService.ClearDocumentDataRequest request) {
            return base.Channel.ClearDocumentData(request);
        }
        
        public void ClearDocumentData(Editor_Prototype.DocumentEditorWebService.Document document) {
            Editor_Prototype.DocumentEditorWebService.ClearDocumentDataRequest inValue = new Editor_Prototype.DocumentEditorWebService.ClearDocumentDataRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.ClearDocumentDataRequestBody();
            inValue.Body.document = document;
            Editor_Prototype.DocumentEditorWebService.ClearDocumentDataResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).ClearDocumentData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataResponse Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap.InitDocumentContentsData(Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataRequest request) {
            return base.Channel.InitDocumentContentsData(request);
        }
        
        public Editor_Prototype.DocumentEditorWebService.Document InitDocumentContentsData(Editor_Prototype.DocumentEditorWebService.Document document, Editor_Prototype.DocumentEditorWebService.DocumentPattern documentPattern) {
            Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataRequest inValue = new Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataRequest();
            inValue.Body = new Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataRequestBody();
            inValue.Body.document = document;
            inValue.Body.documentPattern = documentPattern;
            Editor_Prototype.DocumentEditorWebService.InitDocumentContentsDataResponse retVal = ((Editor_Prototype.DocumentEditorWebService.DocumentEditorServiceSoap)(this)).InitDocumentContentsData(inValue);
            return retVal.Body.InitDocumentContentsDataResult;
        }
    }
}
